# Generated by Django 6.0.1 on 2026-01-24 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_milestone_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIDocumentationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text='Page name (e.g., Dashboard, Profile, Settings)', max_length=255)),
                ('figma_link', models.URLField(blank=True, help_text='Link to Figma page (optional)', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the page and its functionality', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order for displaying pages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_pages', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_documentation_pages', to='projects.project')),
            ],
            options={
                'verbose_name': 'API Documentation Page',
                'verbose_name_plural': 'API Documentation Pages',
                'db_table': 'api_documentation_pages',
                'ordering': ['order', 'page_name'],
                'unique_together': {('project', 'page_name')},
            },
        ),
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='API endpoint name/description', max_length=255)),
                ('endpoint_url', models.CharField(help_text='Full API endpoint URL (e.g., /api/users/list/)', max_length=500)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description of what this API does', null=True)),
                ('request_body', models.TextField(blank=True, help_text='Request body example (JSON format)', null=True)),
                ('response_body', models.TextField(blank=True, help_text='Response body example (JSON format)', null=True)),
                ('request_headers', models.TextField(blank=True, help_text='Required request headers (JSON format)', null=True)),
                ('response_status_codes', models.CharField(blank=True, help_text='Possible response status codes (e.g., 200, 400, 401, 404)', max_length=255, null=True)),
                ('authentication_required', models.BooleanField(default=True, help_text='Whether authentication is required for this endpoint')),
                ('order', models.IntegerField(default=0, help_text='Order for displaying endpoints within the page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_endpoints', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_endpoints', to='projects.apidocumentationpage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_endpoints', to='projects.project')),
            ],
            options={
                'verbose_name': 'API Endpoint',
                'verbose_name_plural': 'API Endpoints',
                'db_table': 'api_endpoints',
                'ordering': ['order', 'name'],
            },
        ),
    ]
