# Generated by Django 6.0.1 on 2026-01-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_apidocumentationpage_apiendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpoint',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes, tips, or important information about this API endpoint', null=True),
        ),
    ]
