# Generated by Django 6.0.1 on 2026-01-13 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Work done today')),
                ('figma_link', models.URLField(blank=True, help_text='Figma link for UI/UX team', null=True)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_updates', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_updates', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Update',
                'verbose_name_plural': 'Daily Updates',
                'db_table': 'daily_updates',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyUpdateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='daily_updates/attachments/')),
                ('file_type', models.CharField(blank=True, help_text='image, document, etc.', max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='daily_updates/thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('daily_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='daily_updates.dailyupdate')),
            ],
            options={
                'verbose_name': 'Daily Update Attachment',
                'verbose_name_plural': 'Daily Update Attachments',
                'db_table': 'daily_update_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyupdate',
            index=models.Index(fields=['project', 'date'], name='daily_updat_project_ac6570_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyupdate',
            index=models.Index(fields=['user', 'date'], name='daily_updat_user_id_1561b5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyupdate',
            index=models.Index(fields=['organization', 'date'], name='daily_updat_organiz_057948_idx'),
        ),
    ]
