# Generated by Django 6.0.1 on 2026-01-13 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=20)),
                ('object_type', models.CharField(choices=[('USER', 'User'), ('PROJECT', 'Project'), ('TASK', 'Task'), ('ATTENDANCE', 'Attendance'), ('LEAVE', 'Leave'), ('PAYROLL', 'Payroll'), ('LEAD', 'Lead')], max_length=20)),
                ('object_id', models.IntegerField()),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_by', 'created_at'], name='audit_logs_action__2a4237_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_logs_object__457405_idx'), models.Index(fields=['organization', 'created_at'], name='audit_logs_organiz_af0d8d_idx'), models.Index(fields=['action_type', 'created_at'], name='audit_logs_action__94af82_idx')],
            },
        ),
    ]
