# Generated by Django 6.0.1 on 2026-01-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text="Employee's date of birth", null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_joining',
            field=models.DateField(blank=True, help_text='Date when employee joined the company', null=True),
        ),
    ]
