# Generated by Django 6.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_birth_date_alter_user_date_of_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Monthly salary (used for payroll generation)',
                max_digits=12,
                null=True,
            ),
        ),
    ]
