# Generated by Django 6.0.1 on 2026-01-13 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', 'Sick Leave'), ('VACATION', 'Vacation/Annual Leave'), ('CASUAL', 'Casual Leave'), ('EMERGENCY', 'Emergency Leave'), ('OTHER', 'Other')], default='CASUAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('days', models.IntegerField(help_text='Number of leave days')),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leaves/attachments/')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leaves',
                'db_table': 'leaves',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='leaves_user_id_cabeb7_idx'), models.Index(fields=['organization', 'date_from'], name='leaves_organiz_bacb46_idx'), models.Index(fields=['status', 'date_from'], name='leaves_status_f92000_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', 'Sick Leave'), ('VACATION', 'Vacation/Annual Leave'), ('CASUAL', 'Casual Leave'), ('EMERGENCY', 'Emergency Leave')], max_length=20)),
                ('year', models.IntegerField()),
                ('total_days', models.IntegerField(default=0)),
                ('used_days', models.IntegerField(default=0)),
                ('remaining_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'db_table': 'leave_balances',
                'ordering': ['-year', 'leave_type'],
                'unique_together': {('user', 'leave_type', 'year')},
            },
        ),
    ]
