# Generated by Django 6.0.1 on 2026-01-24 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin this announcement to the top')),
                ('target_roles', models.JSONField(blank=True, default=list, help_text="List of role names (e.g., ['DEV', 'PM']). Empty list means all roles.")),
                ('attachment', models.FileField(blank=True, help_text='Optional attachment file', null=True, upload_to='announcements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Announcement will be hidden after this date', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BirthdayAnniversary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, help_text='Date when employee joined the company', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_anniversary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Birthday & Anniversary',
                'verbose_name_plural': 'Birthdays & Anniversaries',
                'db_table': 'birthday_anniversaries',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('MEETING', 'Meeting'), ('TRAINING', 'Training'), ('CELEBRATION', 'Celebration'), ('TEAM_BUILDING', 'Team Building'), ('CONFERENCE', 'Conference'), ('WORKSHOP', 'Workshop'), ('OTHER', 'Other')], default='MEETING', max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('venue_link', models.URLField(blank=True, help_text='Online meeting link if virtual', null=True)),
                ('is_virtual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, help_text='Users invited to this event', related_name='events_attending', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('HR', 'HR Policies'), ('IT', 'IT Policies'), ('FINANCE', 'Finance Policies'), ('LEAVE', 'Leave Policies'), ('ATTENDANCE', 'Attendance Policies'), ('CODE_OF_CONDUCT', 'Code of Conduct'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.FileField(help_text='Policy document file (PDF, DOC, etc.)', upload_to='policies/')),
                ('version', models.CharField(default='1.0', help_text='Policy version number', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField(help_text='Date when policy becomes effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'policies',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('NATIONAL', 'National Holiday'), ('REGIONAL', 'Regional Holiday'), ('COMPANY', 'Company Holiday'), ('FESTIVAL', 'Festival'), ('OTHER', 'Other')], default='NATIONAL', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False, help_text='If checked, this holiday repeats every year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'db_table': 'holidays',
                'ordering': ['date'],
                'unique_together': {('organization', 'date', 'name')},
            },
        ),
    ]
