# Generated by Django 6.0.1 on 2026-02-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_recurringholidayrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('NATIONAL', 'National Holiday'), ('REGIONAL', 'Regional Holiday'), ('COMPANY', 'Company Holiday'), ('SATURDAY_OFF', 'Saturday Off'), ('FESTIVAL', 'Festival'), ('OTHER', 'Other')], default='NATIONAL', max_length=20),
        ),
    ]
