# Generated by Django 6.0.1 on 2026-01-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'On Leave'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('WORK_FROM_HOME', 'Work From Home')], default='PRESENT', max_length=20),
        ),
    ]
